# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dfs_pb2 as dfs__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutBlock = channel.stream_unary(
                '/dfs.FileService/PutBlock',
                request_serializer=dfs__pb2.BlockData.SerializeToString,
                response_deserializer=dfs__pb2.BlockResponse.FromString,
                _registered_method=True)
        self.GetBlock = channel.unary_stream(
                '/dfs.FileService/GetBlock',
                request_serializer=dfs__pb2.BlockRequest.SerializeToString,
                response_deserializer=dfs__pb2.BlockData.FromString,
                _registered_method=True)
        self.ReplicateBlock = channel.stream_unary(
                '/dfs.FileService/ReplicateBlock',
                request_serializer=dfs__pb2.BlockData.SerializeToString,
                response_deserializer=dfs__pb2.BlockResponse.FromString,
                _registered_method=True)
        self.SyncBlock = channel.unary_unary(
                '/dfs.FileService/SyncBlock',
                request_serializer=dfs__pb2.BlockRequest.SerializeToString,
                response_deserializer=dfs__pb2.BlockResponse.FromString,
                _registered_method=True)
        self.BecomeLeader = channel.unary_unary(
                '/dfs.FileService/BecomeLeader',
                request_serializer=dfs__pb2.LeaderRequest.SerializeToString,
                response_deserializer=dfs__pb2.LeaderResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PutBlock(self, request_iterator, context):
        """Servicios existentes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateBlock(self, request_iterator, context):
        """Nuevos servicios para replicación Leader-Follower
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BecomeLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.PutBlock,
                    request_deserializer=dfs__pb2.BlockData.FromString,
                    response_serializer=dfs__pb2.BlockResponse.SerializeToString,
            ),
            'GetBlock': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBlock,
                    request_deserializer=dfs__pb2.BlockRequest.FromString,
                    response_serializer=dfs__pb2.BlockData.SerializeToString,
            ),
            'ReplicateBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.ReplicateBlock,
                    request_deserializer=dfs__pb2.BlockData.FromString,
                    response_serializer=dfs__pb2.BlockResponse.SerializeToString,
            ),
            'SyncBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncBlock,
                    request_deserializer=dfs__pb2.BlockRequest.FromString,
                    response_serializer=dfs__pb2.BlockResponse.SerializeToString,
            ),
            'BecomeLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.BecomeLeader,
                    request_deserializer=dfs__pb2.LeaderRequest.FromString,
                    response_serializer=dfs__pb2.LeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfs.FileService/PutBlock',
            dfs__pb2.BlockData.SerializeToString,
            dfs__pb2.BlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfs.FileService/GetBlock',
            dfs__pb2.BlockRequest.SerializeToString,
            dfs__pb2.BlockData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfs.FileService/ReplicateBlock',
            dfs__pb2.BlockData.SerializeToString,
            dfs__pb2.BlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.FileService/SyncBlock',
            dfs__pb2.BlockRequest.SerializeToString,
            dfs__pb2.BlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BecomeLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.FileService/BecomeLeader',
            dfs__pb2.LeaderRequest.SerializeToString,
            dfs__pb2.LeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
