# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\x12\x03\x64\x66s\"W\n\tBlockData\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x13\n\x0bsource_node\x18\x03 \x01(\t\x12\x15\n\rreplica_nodes\x18\x04 \x03(\t\" \n\x0c\x42lockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"1\n\rBlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\rLeaderRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x16\n\x0e\x66ollower_nodes\x18\x02 \x03(\t\"2\n\x0eLeaderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9f\x02\n\x0b\x46ileService\x12\x32\n\x08PutBlock\x12\x0e.dfs.BlockData\x1a\x12.dfs.BlockResponse\"\x00(\x01\x12\x31\n\x08GetBlock\x12\x11.dfs.BlockRequest\x1a\x0e.dfs.BlockData\"\x00\x30\x01\x12\x38\n\x0eReplicateBlock\x12\x0e.dfs.BlockData\x1a\x12.dfs.BlockResponse\"\x00(\x01\x12\x34\n\tSyncBlock\x12\x11.dfs.BlockRequest\x1a\x12.dfs.BlockResponse\"\x00\x12\x39\n\x0c\x42\x65\x63omeLeader\x12\x12.dfs.LeaderRequest\x1a\x13.dfs.LeaderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCKDATA']._serialized_start=18
  _globals['_BLOCKDATA']._serialized_end=105
  _globals['_BLOCKREQUEST']._serialized_start=107
  _globals['_BLOCKREQUEST']._serialized_end=139
  _globals['_BLOCKRESPONSE']._serialized_start=141
  _globals['_BLOCKRESPONSE']._serialized_end=190
  _globals['_LEADERREQUEST']._serialized_start=192
  _globals['_LEADERREQUEST']._serialized_end=249
  _globals['_LEADERRESPONSE']._serialized_start=251
  _globals['_LEADERRESPONSE']._serialized_end=301
  _globals['_FILESERVICE']._serialized_start=304
  _globals['_FILESERVICE']._serialized_end=591
# @@protoc_insertion_point(module_scope)
