namenode:
  host: "34.202.250.249"
  port: 5000

datanodes:
  datanode1:
    host: "3.232.66.23"
    port: 50051
    storage: "/data/node1"
  datanode2:
    host: "44.208.230.35"
    port: 50052
    storage: "/data/node2"
  datanode3:
    host: "54.235.162.161"
    port: 50053
    storage: "/data/node3"
